version: "2.1"
services:
  app:
    build: .
    container_name: lsd-strahler
    restart: unless-stopped
    environment:
      - URL=https://example.com # URL where the app is running
    ports:
      - 3000:3000